spring:
  flyway:
    baseline-on-migrate: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver
  application:
    name: forex-service

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect

openexchangerates-api-key: 27f7301e074543518cdc3ed2d8821676


feign:
  name: forex-feign
  url: https://openexchangerates.org/api/

server:
      port: 8082

